### PR TITLE
Revert "Add list all"

### PR DESCRIPTION
**Pull request by yc2945**
Reverts NYUDevOps-Fall18-Recommendations/recommendations#46

**The code changes is not covered by test cases**

Coverage report: 
Name        Stmts   Miss  Cover   Missing
-----------------------------------------
models.py      76      5    93%   36, 48, 59, 116, 127
server.py      62     27    56%   31, 36-38, 43-45, 50-52, 57-59, 64-66, 75, 89, 116-124, 131
-----------------------------------------
TOTAL         138     32    77%

### CODE REVIEW

**Comment by yc2945** [comment]
Please refer to https://github.com/nyu-devops/lab-restful-flask/blob/master/tests/test_server.py to see how to write proper test case to cover your code.

**Comment by yc2945** [comment]
That sounds good, but I'm not seeing the change. Where did you update it? 
I think it's better to revert your previous change (by merge this pull request) and create a new pull request which contains proper test cases.

**Comment by ameryisafreeelf** [comment]
It should be at the very bottom of test_server in the add-list-all branch

**Comment by ameryisafreeelf** [comment]
add-list-all reverted

**Pull request merged**
