### PR TITLE
Action

### PR DESCRIPTION
**Pull request by rajBandhakavi**

### CODE REVIEW

**Comment by rajBandhakavi** [comment]
Yes, all the items from category A update their category to category B. So, I am trying to update the category id for A to B.

"recommendation.categoryId = data['categoryId']"

The above line updates the categoryId from A to B. The Right hand side, data['categoryId'] contains B which comes from the request.  the left hand side is the category id we want to change

**Comment by yc2945** [comment]
I see. So the new category is not in the URL. Looks good. 

One more suggestion about the routing, "/recommendations/updateCategory/<string:categoryId>" doesn't look very RESTful, maybe consider have something like "/recommendations/<string:columnToUpdate>/<string:newContent>", similar to query_by_category and query_by_product. 
We could handle the 'category' case only and return error if 'columnToUpdate' isn't 'category

**Comment by rajBandhakavi** [comment]
This is a good point. I went back to slides and here is an example that is given there. 

Instead of 
GET http://api.myapp.com/getUser/123
POST http://api.myapp.com/addUser 

we need to be use:
GET http://api.myapp.com/users/123
POST http://api.myapp.com/users

Going by the same logic, our URL instead of  
PUT http://0.0.0.0:5000/recommendations/updateCategory/Comics
should be 
PUT http://0.0.0.0:5000/recommendations/category/Comics.

Do you agree?

**Comment by yc2945** [comment]
Yes, I think that’s what I suggested

**Pull request closed without merging**
