### PR TITLE
update recommendations.feature file

### PR DESCRIPTION
**Pull request by jessiedbq**
update reeommendations.feature file

### CODE REVIEW

**Comment by jessiedbq** [comment]
Update recommendations.feature file: add create, list all, query, update scenarios

**Comment by rajBandhakavi** [comment]
I would really appreciate if we create individual issues for individual functions like create, list all etc and update .feature file appropriately and I feel that would be a more agile way

**Comment by jessiedbq** [comment]
@rajBandhakavi  I'm sorry I didn't read the requirements carefully. I'm totally for your suggestion. But could you please tell me how to delete this change

**Comment by jessiedbq** [comment]
@rajBandhakavi  Never mind, I just thought this request has already been merged into master.

**Comment by rajBandhakavi** [comment]
Thank you

**Pull request closed without merging**
